name: archer
description: |
  Archer data exercise - 7/29/2024
version: 0.0.1
author: bobw@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: archer
  parentArtefactID: archer
  buildSystem: wheel
  author: null
  createdAt: '2024-07-29 19:51:13'
pipelines:
  pipelines/setup:
    name: setup
    description: set up necessary tables, etc
    author: bobw@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-07-29 19:51:13'
    datasets:
      inputs:
      - datasets/raw_body_part
      - datasets/raw_cause_of_inj
      - datasets/raw_claim
      - datasets/raw_claim_status
      - datasets/raw_control_batch
      - datasets/raw_customer1_claim
      - datasets/raw_disability_type
      - datasets/raw_line_of_business
      - datasets/raw_nature_of_inj
      - datasets/raw_treatment_type
      - datasets/raw_type_of_claim
      outputs:
      - datasets/body_part
      - datasets/cause_of_inj
      - datasets/claim
      - datasets/claim_status
      - datasets/control_batch
      - datasets/customer1_claim
      - datasets/disability_type
      - datasets/line_of_business
      - datasets/nature_of_inj
      - datasets/treatment_type
      - datasets/type_of_claim
    subgraphs: []
    dependencies: {}
  pipelines/PoV_Exercise:
    name: PoV_Exercise
    description: ''
    author: bobw@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-07-31 13:43:17'
    datasets:
      inputs:
      - datasets/control_batch
      - datasets/customer1_mapping
      - datasets/customer_claim_file
      outputs:
      - datasets/customer1_claim
    subgraphs: []
    dependencies: {}
  pipelines/PoV_Exercise_ntong:
    name: PoV_Exercise_ntong
    description: null
    author: bobw@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-08-12 19:11:06'
    datasets:
      inputs:
      - datasets/control_batch
      - datasets/customer_claim_file
      outputs:
      - datasets/customer1_claim
    subgraphs: []
    dependencies: {}
  pipelines/PoV_Exercise_basic:
    name: PoV_Exercise_basic
    description: null
    author: bobw@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-08-13 19:40:53'
    datasets:
      inputs:
      - datasets/control_batch
      - datasets/customer_claim_file
      outputs:
      - datasets/customer1_claim
    subgraphs: []
    dependencies: {}
datasets:
  datasets/raw_control_batch:
    name: raw_control_batch
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-07-29 19:56:05'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-07-29 19:56:05'
  datasets/raw_customer1_claim:
    name: raw_customer1_claim
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-07-29 20:37:53'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-07-29 20:37:53'
  datasets/raw_body_part:
    name: raw_body_part
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-07-29 20:46:10'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-07-29 20:46:10'
  datasets/raw_cause_of_inj:
    name: raw_cause_of_inj
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-07-29 20:47:31'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-07-29 20:47:31'
  datasets/raw_claim_status:
    name: raw_claim_status
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-07-29 20:52:04'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-07-29 20:52:04'
  datasets/raw_disability_type:
    name: raw_disability_type
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-07-29 20:53:05'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-07-29 20:53:05'
  datasets/raw_line_of_business:
    name: raw_line_of_business
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-07-29 20:56:52'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-07-29 20:56:52'
  datasets/raw_nature_of_inj:
    name: raw_nature_of_inj
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-07-29 20:57:57'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-07-29 20:57:57'
  datasets/raw_treatment_type:
    name: raw_treatment_type
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-07-29 21:02:38'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-07-29 21:02:38'
  datasets/raw_type_of_claim:
    name: raw_type_of_claim
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-07-29 21:03:41'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-07-29 21:03:41'
  datasets/raw_claim:
    name: raw_claim
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-07-29 21:25:48'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-07-29 21:25:48'
  datasets/control_batch:
    name: control_batch
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-07-29 21:48:34'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Database
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-07-29 21:48:34'
  datasets/customer1_claim:
    name: customer1_claim
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-07-29 21:49:34'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Database
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-07-29 21:49:34'
  datasets/body_part:
    name: body_part
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-07-29 21:50:25'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Database
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-07-29 21:50:25'
  datasets/cause_of_inj:
    name: cause_of_inj
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-07-29 21:51:14'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Database
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-07-29 21:51:14'
  datasets/claim_status:
    name: claim_status
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-07-29 21:52:08'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Database
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-07-29 21:52:08'
  datasets/disability_type:
    name: disability_type
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-07-29 21:53:00'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Database
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-07-29 21:53:00'
  datasets/line_of_business:
    name: line_of_business
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-07-29 21:53:47'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Database
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-07-29 21:53:47'
  datasets/nature_of_inj:
    name: nature_of_inj
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-07-29 21:54:28'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Database
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-07-29 21:54:28'
  datasets/treatment_type:
    name: treatment_type
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-07-29 21:55:04'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Database
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-07-29 21:55:04'
  datasets/type_of_claim:
    name: type_of_claim
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-07-29 21:55:39'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Database
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-07-29 21:55:39'
  datasets/claim:
    name: claim
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-07-29 21:56:33'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Database
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-07-29 21:56:33'
  datasets/customer_claim_file:
    name: customer_claim_file
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-07-31 13:51:03'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-07-31 13:51:03'
  datasets/raw_claim_1:
    name: raw_claim_1
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-08-08 20:25:55'
    mode: stream
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-08-08 20:25:56'
  datasets/customer_claim_file_stream:
    name: customer_claim_file_stream
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-08-08 20:30:04'
    mode: stream
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Database
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-08-08 20:30:04'
  datasets/customer1_mapping:
    name: customer1_mapping
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-08-12 15:57:38'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-08-12 15:57:38'
  datasets/stage_claim_table:
    name: stage_claim_table
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-08-12 20:21:02'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Database
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-08-12 20:21:02'
templates: {}
jobs:
  jobs/JobTest1:
    name: JobTest1
    description: ''
    fabricUID: 9631
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-08-14 14:59:05'
    author: bobw@prophecy.io
    models: []
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-07-29 19:51:13'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-08-08T20:17:13.057723Z'
  name: plibMaven
  version: 8.0.31
  id: '1218097084'
  createdAt: '2024-08-08T20:17:13.057577Z'
  enabled: true
  entity: Project
- type: plibPypi
  modifiedAt: '2024-08-14T14:56:52.435Z'
  name: ProphecyLibsPython
  version: 1.9.9
  id: '1326775046'
  createdAt: '2024-08-08T20:17:13.057862Z'
  enabled: true
  entity: Project
  description: Default dependency for Prophecy Libs
  scope: Project
  editable: true
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.26
    isDefault: true
    author: null
    createdAt: '2024-08-12 12:53:20'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-07-29 19:49:52'
  '12656':
    projectUID: 12656
    projectName: ProphecyStreamingPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12656.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2024-08-08 20:17:11'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
